- name: deploy all
  hosts: all
  roles:
    - base
    - admins
    - kvm-guest

- name: deploy backup
  hosts: backup
  roles:
    - backup-service

- name: deploy operations
  hosts: operations
  roles:
    - backup-object
    - docker
    - deployment-target

- name: prune operations
  hosts: operations
  roles:
    - prune-docker

- name: cleanup all
  hosts: all
  roles:
    - cleanup-reboot
