- name: deploy base
  hosts: all
  roles:
    - base
    - kvm-guest

- name: deploy operations
  hosts: operations
  roles:
    - backup-object
    - docker
    - logging
    - gate
    - deployment-target

- name: 'deploy operations : prune docker'
  hosts: operations
  roles:
    - prune-docker

- name: deploy backup
  hosts: backup
  roles:
    - backup-service
