- name: deploy base
  hosts: all
  roles:
    - base

- name: deploy docker
  hosts: docker
  roles:
    - docker
    - logging
    - backup
    - gate

- name: 'prune docker'
  hosts: docker
  roles:
    - prune-docker
