- name: 'install borg'
  get_url:
    url: https://github.com/borgbackup/borg/releases/download/1.1.10/borg-linux64
    dest: /usr/local/bin/borg
    checksum: sha256:6338d67aad4b5cd327b25ea363e30f0ed4abc425ce2d6a597c75a67a876ef9af
    mode: '0755'

- name: 'install packages'
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - socat

- name: 'deploy utilities'
  copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  with_items:
    - run-with-snapshot.sh
    - backup-on-pull.sh

- name: 'configure authorized keys'
  authorized_key:
    user: root
    path: /root/.ssh/authorized_keys.backup
    key: "{{ backup_authorized_keys | join('\n') }}"
    key_options: 'command="backup-on-pull.sh",from="{{ groups[''backup''] | default([]) | map(''extract'', hostvars, [''ansible_host'']) | join('','') }}",restrict,port-forwarding'
    exclusive: true
    manage_dir: false
