- name: 'backup : network'
  docker_network:
    name: core_backup

- name: 'backup : container'
  docker_container:
    name: core_backup
    image: quay.io/process_team/docker_backup:latest
    pull: '{{ docker_pull | default(false) | bool }}'
    restart_policy: 'on-failure'
    restart_retries: 5
    state: started
    env:
      CONFIG_INTERVAL: '{{ backup_interval }}'
      CONFIG_FULL_EVERY: '{{ backup_full_every }}'
      CONFIG_REMOVE_OLDER_THAN: '{{ backup_remove_older_than }}'
      CONFIG_STORAGE_URL: '{{ backup_storage_url }}/{{ base_name_host }}'
      CONFIG_STORAGE_PASSWORD: '{{ backup_storage_password | default("") }}'
      CONFIG_STORAGE_KEY_ID: '{{ backup_storage_key_id | default("") }}'
      CONFIG_STORAGE_SECRET_KEY: '{{ backup_storage_secret_key | default("") }}'
    volumes:
      - '/:/host:ro'
      - '{{ base_data_dir }}/core_backup/backups/:/backups'
      - '{{ base_data_dir }}/core_backup/backups-tmp/:/backups-tmp'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - name: bridge
      - name: core_backup
    purge_networks: true
