- name: 'project facts'
  set_fact:
    project:
      mode:     '{{ project_mode }}'
      branch:   '{{ project_branch }}'
      version:  '{{ project_version }}'
      group:    '{{ project_group }}'
      name:     '{{ project_name }}'
      images:   '{{ project_images | default({}) }}'
      domains:  '{{ project_domains }}'
      services: '{{ project_services }}'
      expose:   '{{ project_expose | default({}) }}'
      backup:   '{{ project_backup | default({}) }}'
