- name: 'gate : network'
  docker_network:
    name: core_gate

- name: 'gate : container'
  docker_container:
    name: core_gate
    image: traefik:latest
    pull: '{{ docker_pull | default(false) | bool }}'
    restart_policy: 'on-failure'
    restart_retries: 5
    state: started
    command: >
      --acme=true
      --acme.onhostrule=true
      --acme.email={{ base_devops_email }}
      --acme.storage=/certs/acme.json
      --acme.entrypoint=https
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entrypoints='Name:https Address::443 TLS'
      --defaultentrypoints=https,http
      --docker=true
      --docker.exposedbydefault=false
      --docker.watch=true
      --web=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/core_gate/certs/:/certs'
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
    networks:
      - name: bridge
      - name: core_gate
    purge_networks: true

# configure firewall
- name: 'gate : allow http and https traffic'
  lineinfile:
    dest: '/etc/{{ item[0] }}/rules'
    line: '{{ item[1] }}'
  with_nested:
    - [ 'shorewall', 'shorewall6' ]
    - - 'ACCEPT all fw tcp 80'
      - 'ACCEPT all fw tcp 443'
  notify: restart shorewall

- meta: flush_handlers
