- name: 'gate : network'
  docker_network:
    name: core_gate

- name: 'gate : container'
  docker_container:
    name: core_gate
    image: traefik:latest
    pull: '{{ docker_pull | default(false) | bool }}'
    restart_policy: 'unless-stopped'
    state: started
    command: >
      {% if gate_disable_tls | default(false) %}
      --entrypoints='Name:http Address::80'
      --defaultentrypoints=http
      {% else %}
      --acme=true
      --acme.onhostrule=true
      --acme.email={{ base_devops_email }}
      --acme.storage=/certs/acme.json
      --acme.entrypoint=https
      --entrypoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entrypoints='Name:https Address::443 TLS'
      --defaultentrypoints=https,http
      {% endif %}
      --docker=true
      --docker.exposedbydefault=false
      --docker.watch=true
      --web=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/data/core_gate/certs/:/certs'
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
    networks:
      - name: bridge
      - name: core_gate
    purge_networks: true
