- name: 'project build : build image'
  shell: |
    docker build \
    --cache-from "{{ project | project_get_image_repository(image) }}:{{ project | project_get_image_tag_latest(image) }}" \
    --file "{{ project | project_get_image_dockerfile(image, project_source) }}" \
    --tag "{{ project | project_get_image_repository(image) }}:{{ project | project_get_image_tag(image) }}" \
    --tag "{{ project | project_get_image_repository(image) }}:{{ project | project_get_image_tag_latest(image) }}" \
    {% for key, value in (project | project_get_image_buildargs(image)).iteritems() %} --build-arg "{{ key }}={{ value }}" {% endfor %} \
    "{{ project | project_get_image_path(image, project_source) }}"
  with_items: '{{ project | project_get_images }}'
  loop_control:
    loop_var: image
  async: 3600
  poll: 0
  register: build_wait

- name: 'project build : build image : wait'
  async_status:
    jid: '{{ item.ansible_job_id }}'
  with_items: '{{ build_wait.results }}'
  register: build_results
  until: build_results.finished
  retries: 360
  delay: 10
