- name: 'project build : push image'
  docker_image:
    name: '{{ project | project_get_image_repository(image) }}'
    tag: '{{ project | project_get_image_tag(image) }}'
    push: '{{ docker_push | default(false) | bool }}'
  with_items: '{{ project | project_get_images }}'
  loop_control:
    loop_var: image
  async: 3600
  poll: 0
  register: push_wait

- name: 'project build : push image : wait'
  async_status:
    jid: '{{ item.ansible_job_id }}'
  with_items: '{{ push_wait.results }}'
  register: push_results
  until: push_results.finished
  retries: 360
  delay: 10
