- name: 'logging : container'
  docker_container:
    name: core_logging
    image: iamatypeofwalrus/logspout-loggly:latest
    # TODO: we want true here, but this results in 'changed' status even if nothing changed
    pull: false
    restart_policy: 'on-failure'
    restart_retries: 5
    state: started
    env:
      LOGGLY_TOKEN: '{{ logging_token }}'
      LOGGLY_TAGS: '{{ base_name_host }}.{{ base_name_domain }}'
      FILTER_NAME: '*'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - name: bridge
    purge_networks: true
