- name: 'repository : add key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: 'repository : add repository and update cache'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable'
    update_cache: yes
