- name: 'reboot system (if required)'
  command: bash -c "screen -d -m bash -c 'service ssh stop; sleep 7; shutdown --reboot now'; sleep 1"
  args:
    removes: '/var/run/reboot-required'

- name: 'reboot system : wait for reboot'
  local_action: wait_for host="{{ ansible_host }}" port="{{ ansible_port | default(22) }}" delay=14

- name: 'purge old kernels'
  command: purge-old-kernels -qy
  register: 'command_purge_old_kernels'
  changed_when: "'No kernels are eligible for removal' not in command_purge_old_kernels.stdout"
