- name: 'project deploy : network'
  docker_network:
    name: '{{ project | project_get_network }}'

- name: 'project deploy : container'
  docker_container:
    name:     '{{ project | project_get_service_name(service) }}'
    image:    '{{ project | project_get_service_image(service) }}'
    pull:     '{{ docker_pull | default(false) | bool }}'
    env:      '{{ project | project_get_service_env(service) }}'
    labels:   '{{ project | project_get_service_labels(service) }}'
    volumes:  '{{ project | project_get_service_volumes(service) }}'
    networks: '{{ project | project_get_service_networks(service) }}'
    purge_networks: true
    restart_policy: 'on-failure'
    restart_retries: 5
  with_items: '{{ project | project_get_services }}'
  loop_control:
    loop_var: service
    pause: 1
