- name: 'project deploy : network'
  docker_network:
    name: '{{ project | project_get_network }}'

- include: service-pull.yml
  with_items: '{{ project | project_get_services }}'
  loop_control:
    loop_var: service
    pause: 1

- include: service-deploy.yml
  with_items: '{{ project | project_get_services }}'
  loop_control:
    loop_var: service
    pause: 1
