- name: 'project deploy : image : {{ service }}'
  docker_image:
    name: '{{ project | project_get_service_image(service) }}'
    force: true
  async: 3600
  poll: 0
  register: pull_wait

- name: 'project deploy : image : {{ service }} : wait'
  async_status:
    jid: '{{ pull_wait.ansible_job_id }}'
  register: pull_result
  until: pull_result.finished
  retries: 360
  delay: 10
