- name: 'configure names : configure names and dns in dhclient.conf'
  blockinfile:
    dest: /etc/dhcp/dhclient.conf
    block: |
      supersede host-name "{{ inventory_hostname }}";
      supersede domain-name "{{ base_domain }}";
      supersede domain-search "{{ base_domain }}";
      supersede domain-name-servers 8.8.8.8;
  notify: reboot system

- name: 'configure names : configure hosts file'
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname }}.{{ base_domain }} {{ inventory_hostname }}'
  notify: reboot system

- name: 'configure names : configure host-name'
  hostname:
    name: '{{ inventory_hostname }}'
  notify: reboot system
