# purge shorewall

- name: 'configure firewall : remove shorewall'
  apt: name='{{item}}' purge=yes state=absent
  with_items:
    - shorewall
    - shorewall6
  notify: reboot system

- name: 'configure firewall : remove shorewall configuration'
  file:
    state: absent
    path: "/etc/{{ item }}"
  with_items:
    - shorewall
    - shorewall6
  notify: reboot system

# setup new system

- name: 'configure firewall : deploy scripts'
  copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  with_items:
    - packetfilter.sh
    - packetfilter-helper.sh
  notify: restart packetfilter

- name: 'configure firewall : create config directory'
  file:
    path: '/etc/packetfilter'
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: restart packetfilter

- name: 'configure firewall : deploy config'
  copy:
    src: 'packetfilter-config-base.sh'
    dest: '/etc/packetfilter/00-base.sh'
    owner: root
    group: root
    mode: 0755
  notify: restart packetfilter

- name: 'configure firewall : deploy systemd service file'
  copy:
    src: 'packetfilter.service'
    dest: /lib/systemd/system/
    owner: root
    group: root
    mode: 0644
  notify: restart packetfilter

- name: 'configure firewall : enable packetfilter service'
  command: 'systemctl enable /lib/systemd/system/packetfilter.service'
  register: task_enable_packetfilter_result
  changed_when: "'Created symlink' in task_enable_packetfilter_result.stderr"
  notify: restart packetfilter
