- name: 'install essentials'
  apt: name='{{item}}' state=latest
  with_items:
    - sysfsutils
    - apt-transport-https
    - ca-certificates
    - screen
    - nano
    - elvis-tiny
    - mc
    - curl
    - jq
