- name: 'install essentials'
  apt: name='{{item}}' state=latest
  with_items:
    - sysfsutils
    - apt-transport-https
    - ca-certificates
    - screen
    - nano
    - elvis-tiny
    - mc
    - curl
    - jq
    - net-tools
    - shorewall
    - shorewall6
    - python-pip
    - python-virtualenv
    - exim4
    - byobu
    - rdiff-backup
    - reboot-notifier
    - needrestart

- name: 'install essentials : pip and toposort'
  pip: name='{{item}}' state=latest
  with_items:
    - pip
    - toposort
