- name: 'upgrade system : upgrade now'
  apt:
    update_cache: yes
    upgrade: dist

- name: 'upgrade system : install unattended-upgrades'
  apt:
    name: unattended-upgrades
    state: latest

- name: 'upgrade system : configure unattended-upgrades'
  blockinfile:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    state: present
    create: yes
    block: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
