# naming parts used for service and network names
project_group: example
project_name: simple

# images to be build and registered
project_images:
  app:
    dockerfile: Dockerfile
    repository: quay.io/process_team/example-simple-app

# domains used to serve the application
project_domains:
  staging: staging.simple-example.local
  production: simple-example.local

# hosts used to serve the application
project_target:
  staging: staging.server.example.local
  production: production.server.example.local

# service composition (will be connected through their own network)
project_services:
  web:
    image: 'project:app'
    depends_on:
      - db
  db:
    image: 'mongo:latest'
    volumes:
      - source: 'service:/db'
        destination: '/data/db'

# services to be exposed via reverse proxy
project_expose:
  web:
    - type: http
      port: 3000
      domains:
        - '@'
        - www

# backups to be performed
project_backup:
  db:
    dbdata:
      type: mongodb
      port: 27017
